import "./globals.css";
import { roboto, anton, quattro } from './fonts';
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Genrobotics",
  description: "Generated by Next JS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icons/favicon.svg" sizes="any" />
      </head>
      <body className={`${roboto.variable} ${anton.variable} ${quattro.variable} bg-black font-roboto`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
} 